---
- name: Get unused FortiGate firewall rules since X days ago
  hosts: fortigate
  gather_facts: no
  connection: local
  
  vars:
    cutoff_days: 7  # Modifier ici pour changer le nombre de jours
    vdom: "root"
    output_file: "/home/dhia/Desktop/createfirewall/jinjatest/unused_rules_{{ cutoff_days }}days.txt"

  tasks:

    - name: Get current epoch timestamp (controller-side)
      command: date +%s
      delegate_to: localhost
      register: current_epoch_result

    - name: Set current and cutoff epoch
      set_fact:
        current_epoch: "{{ current_epoch_result.stdout | int }}"
        cutoff_epoch: "{{ (current_epoch_result.stdout | int) - (cutoff_days * 86400) }}"

    - name: Get firewall policy stats from FortiGate
      uri:
        url: "http://{{ inventory_hostname }}/api/v2/monitor/firewall/policy?vdom={{ vdom }}"
        method: GET
        headers:
          Authorization: "Bearer {{ hostvars[inventory_hostname]['ansible_httpapi_token'] }}"
        return_content: yes
        validate_certs: no
      register: policy_response

    - name: Filter rules unused since cutoff (using loop)
      set_fact:
        unused_rules: >-
          [{% for rule in policy_response.json.results
               if rule.last_used is defined and (rule.last_used | int) < (cutoff_epoch | int) %}
              {{ rule }},
           {% endfor %}]

    - name: Debug unused rules (optional)
      debug:
        var: unused_rules

    - name: Save unused rules to file
      copy:
        content: |
          {% for rule in unused_rules %}
          ID: {{ rule.policyid }},
          Last Used: {{ rule.last_used }},
          Bytes: {{ rule.bytes }},
          Hit Count: {{ rule.hit_count }},
          Comments: {{ rule.comments | default('N/A') }}
          -----------------------------
          {% endfor %}
        dest: "{{ output_file }}"
      delegate_to: localhost
