- name: Enable split VDOM mode on FortiGate
  hosts: fortigate
  gather_facts: false
  connection: httpapi

  vars_files:
    - vars/ports.vars  # This imports the ports variable from the external ports.vars file

  tasks:
    - name: Set VDOM mode to split-vdom
      fortinet.fortios.fortios_system_global:
        vdom: "root"
        system_global:
          vdom_mode: "split-vdom"
      register: vdom_mode_change

    - name: Pause for 10 seconds before proceeding
      pause:
        seconds: 10

    - name: Wait for FortiGate to come back online (optional)
      wait_for:
        host: "{{ inventory_hostname }}"
        port: 443
        delay: 30
        timeout: 300
      delegate_to: localhost
      when: vdom_mode_change.changed

    - name: Create VDOM named FG-traffic
      fortinet.fortios.fortios_system_vdom:
        vdom: "root"
        state: present
        system_vdom:
          name: "FG-traffic"

    - name: Assign interfaces to FG-traffic VDOM
      fortinet.fortios.fortios_system_interface:
        vdom: "root"
        state: present
        system_interface:
          name: "{{ item.name }}"
          vdom: "{{ item.vdom }}"
          ip: "{{ item.ip }}"
          allowaccess: "{{ item.allowaccess }}"
      loop: "{{ ports }}"


